# This is a basic workflow to help you get started with Actions

name: 'Prepare Deploy'

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ master ]
  check_run:
    types: [rerequested, requested_action]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy:
    # if: github.event.requested_action.identifier == 'deploy'
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Deploy to S3
      run: |
        # aws s3 sync ./build/ ${{ secrets.S3_BUCKET }}
        echo hi "${{ toJson(github.event) }}"

  # This workflow contains a single job called "build"
  build:
    if: github.event_name == 'push'
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Create deploy button
      run: |
        curl --silent --output /dev/null --show-error --fail -X POST -H 'Accept: application/vnd.github.antiope-preview+json' -H 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' -H 'Content-Type: application/json' --data '{"name":"Deploy button","head_sha":${{ toJson(github.sha) }},"status":"queued","actions":[{"label":"Deploy to S3","identifier":"deploy","description":"Deploy to S3"}]}' 'https://api.github.com/repos/${{ github.repository }}/check-runs'
